-- Insert recipes --
INSERT INTO recipe (ID, title, instructions) VALUES
(4, 'Tropical Sunrise Boost', 'Blend 200 milliliters of mango juice, 150 milliliters of orange juice, and 100 milliliters of pineapple juice. Add 50 grams of passionfruit pulp. Mix thoroughly and serve chilled.'),
(5, 'Mediterranean Green Detox', 'Combine 100 grams of cucumber, 50 grams of kale, 150 milliliters of green apple juice, and 10 grams of fresh mint. Blend until smooth and serve immediately.'),
(6, 'Berry Bliss Medley', 'Blend 100 grams each of blueberries, raspberries, strawberries, and blackcurrants with 200 milliliters of water. Add 20 grams of honey and mix until smooth.'),
(7, 'Golden Turmeric Elixir', 'Combine 200 milliliters of carrot juice, 150 milliliters of orange juice, 5 grams of turmeric, 2 grams of ginger, and a pinch of black pepper. Mix well and serve chilled.'),
(8, 'Island Green Paradise', 'Blend 150 grams of spinach, 100 grams of green papaya, 50 grams of kiwi, and 10 milliliters of lime juice with 300 milliliters of water.'),
(9, 'Red Beet Energy Shot', 'Combine 100 milliliters of beet juice, 100 milliliters of pomegranate juice, and 10 grams of ginger. Mix and serve as a shot.'),
(10, 'Zesty Citrus Cooler', 'Mix 200 milliliters of lemon juice, 150 milliliters of grapefruit juice, 100 milliliters of tangerine juice, and a pinch of Himalayan salt. Serve chilled.'),
(11, 'Asian Pear Harmony', 'Blend 150 grams of Asian pears, 50 grams of lychee, 5 grams of ginger, and 20 grams of honey with 200 milliliters of water.'),
(12, 'Spiced Chai Carrot Delight', 'Mix 200 milliliters of carrot juice, 100 milliliters of apple juice, 2 grams of cinnamon, and 1 gram of cardamom. Blend until smooth.'),
(13, 'Brazilian Açai Energy', 'Blend 100 grams of açai berries, 200 milliliters of coconut water, 50 grams of banana, and 50 grams of blueberries until smooth.'),
(14, 'Alpine Orchard Blend', 'Mix 150 milliliters of Swiss apple juice, 150 milliliters of pear juice, and 10 milliliters of elderflower extract. Serve chilled.'),
(15, 'African Baobab Boost', 'Combine 100 grams of baobab fruit pulp, 200 milliliters of orange juice, 100 milliliters of guava juice, and 100 milliliters of mango juice. Blend until smooth.'),
(16, 'Matcha Mint Fusion', 'Mix 2 grams of matcha powder, 100 grams of cucumber, 20 milliliters of lime juice, and 10 grams of fresh mint with 300 milliliters of water. Blend thoroughly.'),
(17, 'Caribbean Pineapple Punch', 'Blend 200 milliliters of pineapple juice, 150 milliliters of coconut water, 20 milliliters of lime juice, and 100 milliliters of guava juice.'),
(18, 'Cranberry Kiwi Cleanse', 'Blend 200 milliliters of cranberry juice, 50 grams of kiwi, and 20 grams of honey until smooth.'),
(19, 'Peruvian Purple Sweetness', 'Combine 100 grams of Peruvian purple corn, 100 grams of grapes, and 50 grams of blackberries with 300 milliliters of water. Blend until smooth.'),
(20, 'Nordic Berry Vitality', 'Blend 100 grams each of lingonberries, cloudberries, and raspberries with 300 milliliters of water. Add honey to taste.'),
(21, 'Thai Basil Citrus Zing', 'Combine 200 milliliters of pineapple juice, 150 milliliters of orange juice, 10 milliliters of lemon juice, and 5 grams of Thai basil. Blend well.'),
(22, 'Moroccan Mint Limeade', 'Mix 200 milliliters of lime juice, 5 grams of Moroccan green tea, and 10 grams of fresh mint with 200 milliliters of water. Chill before serving.'),
(23, 'Arctic Charcoal Detox', 'Mix 2 grams of activated charcoal, 200 milliliters of lemon juice, and 20 milliliters of Canadian maple syrup. Shake well and serve chilled.');

-- Insert products --
INSERT INTO product (ID, title, description, price, recipe_id) VALUES
(4, 'Tropical Sunrise Boost', 'Start your day with a vibrant blend of mango, pineapple, orange, and passionfruit. Packed with immune-boosting Vitamin C and tropical flavors sourced from Brazil, Thailand, and Costa Rica, this juice will leave you refreshed and energized.', 6.99, 4),
(5, 'Mediterranean Green Detox', 'A rejuvenating fusion of cucumber, kale, green apple, and fresh mint, inspired by the gardens of the Mediterranean. This juice is rich in antioxidants, perfect for a gentle detox.', 7.49, 5),
(6, 'Berry Bliss Medley', 'A delightful mix of blueberries, raspberries, strawberries, and blackcurrants from North America and Europe. High in fiber and antioxidants, this juice is a berry lover’s dream.', 6.99, 6),
(7, 'Golden Turmeric Elixir', 'A nourishing blend of turmeric, ginger, carrot, and orange with a hint of black pepper to enhance absorption. Ingredients sourced from India, South America, and the USA for ultimate inflammation-fighting power.', 7.99, 7),
(8, 'Island Green Paradise', 'Sip into a tropical escape with spinach, green papaya, kiwi, and lime. This powerhouse juice is packed with iron, Vitamin K, and a touch of zest from the islands.', 7.29, 8),
(9, 'Red Beet Energy Shot', 'A bold combination of beets, pomegranate, and ginger for a natural energy boost. Rich in nitrates and antioxidants, this juice promotes stamina and heart health.', 6.79, 9),
(10, 'Zesty Citrus Cooler', 'A tangy and hydrating blend of lemon, grapefruit, tangerine, and a dash of Himalayan salt for electrolytes. Perfect as a post-workout refreshment.', 6.49, 10),
(11, 'Asian Pear Harmony', 'Experience the sweet and delicate flavor of Asian pears blended with lychee, ginger, and honey. This juice brings together ingredients from East Asia for a unique, soothing experience.', 7.49, 11),
(12, 'Spiced Chai Carrot Delight', 'A warming blend of carrots, apples, cinnamon, and a hint of cardamom. Inspired by Indian chai flavors, this juice is as comforting as it is nourishing.', 7.69, 12),
(13, 'Brazilian Açai Energy', 'Packed with superfood açai berries, coconut water, banana, and blueberries. This vibrant juice delivers natural energy and a dose of powerful antioxidants.', 8.49, 13),
(14, 'Alpine Orchard Blend', 'A refreshing combination of Swiss apples, pears, and elderflower, inspired by the crisp flavors of the Alps. A light yet flavorful juice for any time of day.', 6.89, 14),
(15, 'African Baobab Boost', 'Enjoy the tangy and nutrient-rich baobab fruit combined with oranges, guava, and mango. A taste of Africa in a bottle, loaded with Vitamin C and calcium.', 7.99, 15),
(16, 'Matcha Mint Fusion', 'Green tea matcha meets cucumber, lime, and fresh mint in this invigorating drink. A light, hydrating juice with a subtle caffeine boost sourced from Japan.', 8.29, 16),
(17, 'Caribbean Pineapple Punch', 'An exotic mix of pineapple, coconut, lime, and guava, straight from the Caribbean islands. This tropical punch is as hydrating as it is flavorful.', 6.99, 17),
(18, 'Cranberry Kiwi Cleanse', 'A tart yet sweet combination of cranberries, kiwis, and a touch of honey. Packed with Vitamin C and great for supporting urinary health.', 7.19, 18),
(19, 'Peruvian Purple Sweetness', 'Featuring antioxidant-rich Peruvian purple corn, grapes, and blackberries. A uniquely sweet and earthy juice to support overall health.', 7.79, 19),
(20, 'Nordic Berry Vitality', 'A Scandinavian-inspired blend of lingonberries, cloudberries, and raspberries. High in antioxidants and full of tart yet refreshing flavors.', 8.49, 20),
(21, 'Thai Basil Citrus Zing', 'An exotic mix of Thai basil, pineapple, orange, and lemon. This juice is zesty, fragrant, and loaded with immune-boosting properties.', 7.39, 21),
(22, 'Moroccan Mint Limeade', 'Cool down with a refreshing blend of mint, lime, and a hint of Moroccan green tea. A revitalizing, low-calorie drink with a touch of North African inspiration.', 6.99, 22),
(23, 'Arctic Charcoal Detox', 'A cleansing blend of activated charcoal, lemon, and Canadian maple syrup. This juice is designed to gently detoxify and leave you feeling renewed.', 8.19, 23);